#!/bin/bash

chmod 755 ./mod-publishManager/mk
chmod 755 ./mod-sessionManager/mk
chmod 755 ./mod-nodeWatcher/mk
chmod 755 ./mod-subRedis/mk
chmod 755 ./mod-sockServer/mk
chmod 755 ./mod-webServer/mk

echo "done."
