#!/bin/bash

CUR_DIR="`pwd -P`"

echo " >> mod-publishManager"
cd ./mod-publishManager
./mk clean eclipse

echo " >> mod-sessionManager"
cd ../mod-sessionManager
./mk clean eclipse

echo " >> mod-nodeWatcher"
cd ../mod-nodeWatcher
./mk clean eclipse

echo " >> mod-subRedis"
cd ../mod-subRedis
./mk clean eclipse

echo " >> mod-sockServer"
cd ../mod-sockServer
./mk clean eclipse

echo " >> mod-webServer"
cd ../mod-webServer
./mk clean eclipse

cd $CUR_DIR


echo "done."
